### ISSUE TITLE
`<My_Factory>#build` does not create a valid object

### ISSUE THREAD

**Issue by TomasBarry** [Quramy/prisma-fabbrica#357]
**Describe the bug**
If I have a Prisma model with non-nullable columns with default values, and I build the object, those attributes are not set.

**To Reproduce**
```prisma
model User {
  firstName String @default('Something')
}
```

```typescript
const user = UserFactory.build()

console.log(user.firstName)
=> undefined
```

**Expected behavior**

I would expect `user.firstName` to return `'Something'`

**Environment (please complete the following information):**

- Database kind PostgreSQL
- Node.js version v18.16.0
- `@prisma/client` version 5.1.0
- TypeScript Version 5.1.3

### Note

If this is intended behaviour then that's fine. From my experience with `FactoryBot` in Rails etc, which this seems to be inspired by, then `build` _should_ create a valid object

**Comment by Quramy** [comment]
Thanks for describing this issue.

> If this is intended behaviour then that's fine. 

Yes.  The `build`  method provides data set to create the model. 
https://github.com/Quramy/prisma-fabbrica?tab=readme-ov-file#build-input-data-only

The build method only prepares the minimum data required for `prisma.user.create` .

In your example, fabbrica does not generate the `firstName` field value because this is an optional field and the default value is filled by Prisma Client engine.
